// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHeroList() {
  return window['go']['main']['App']['GetHeroList']();
}

export function GetImageUrlsById(arg1) {
  return window['go']['main']['App']['GetImageUrlsById'](arg1);
}

export function GetRandomImageUrl() {
  return window['go']['main']['App']['GetRandomImageUrl']();
}
