// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHeroList():Promise<Array<string>>;

export function GetImageUrlsById(arg1:string):Promise<Array<string>>;

export function GetRandomImageUrl():Promise<string>;
